//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MertKalKisisel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adminler
    {
        public int Id { get; set; }
        public string AdminKullaniciAdi { get; set; }
        public string Sifre { get; set; }
        public string Facebook { get; set; }
        public string Twitter { get; set; }
        public string İnstagram { get; set; }
        public string email { get; set; }
        public string googlehesap { get; set; }
        public virtual bool BeniHatirla { get; set; }
    }
}
