//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MertKalKisisel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HAKKIMDA
    {
        public int Id { get; set; }
        public string baslik { get; set; }
        public string aciklama { get; set; }
        public string cv { get; set; }
        public string foto { get; set; }
    }
}
