//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MertKalKisisel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iletisim
    {
        public int Id { get; set; }
        public string Ad { get; set; }
        public string email { get; set; }
        public string telno { get; set; }
        public string mesaj { get; set; }
    }
}
