//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MertKalKisisel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class İlgiAlanlari
    {
        public int ilgiAlaniID { get; set; }
        public string ilgiAlanlarim { get; set; }
        public string foto { get; set; }
    }
}
