//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MertKalKisisel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KalMertModelEntities : DbContext
    {
        public KalMertModelEntities()
            : base("name=KalMertModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adminler> Adminler { get; set; }
        public virtual DbSet<HAKKIMDA> HAKKIMDA { get; set; }
        public virtual DbSet<iletisim> iletisim { get; set; }
        public virtual DbSet<İlgiAlanlari> İlgiAlanlari { get; set; }
        public virtual DbSet<Projeler> Projeler { get; set; }
        public virtual DbSet<Tanitim> Tanitim { get; set; }
        public virtual DbSet<Yeteneklerim> Yeteneklerim { get; set; }
    }
}
