//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MertKalKisisel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projeler
    {
        public int IDProje { get; set; }
        public string ProjeAd { get; set; }
        public string ProjeAciklama { get; set; }
        public string ProjeResim { get; set; }
        public Nullable<System.DateTime> eklemetarihi { get; set; }
    }
}
