//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MertKalKisisel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tanitim
    {
        public int ID { get; set; }
        public string AdSoyad { get; set; }
        public string lise { get; set; }
        public string uni { get; set; }
        public string unvan { get; set; }
        public string foto { get; set; }
        public string telno { get; set; }
        public string adress { get; set; }
        public string email { get; set; }
    }
}
